DROP TABLE IF EXISTS WORKSHOP_RECEIPTS;
DROP TABLE IF EXISTS CAR;

create table CAR
(
    id               INT,
    brand            VARCHAR(20),
    model            VARCHAR(20),
    color            VARCHAR(20),
    car_registration VARCHAR(9) PRIMARY KEY
);

create table WORKSHOP_RECEIPTS
(
    id               INT GENERATED BY DEFAULT AS IDENTITY not null,
    car_registration VARCHAR(9),
    start_date       TIMESTAMP,
    end_date         TIMESTAMP,
    price_of_pieces  DOUBLE,
    hourly_rate      DOUBLE,
    curr             VARCHAR(3),
    description      VARCHAR(150),
    FOREIGN KEY (car_registration) REFERENCES CAR (car_registration)
);

INSERT INTO CAR (id, brand, model, color, car_registration)
VALUES (1, 'Toyota', 'Corolla', 'Azul', 'ABC123'),
       (2, 'Ford', 'Mustang', 'Rojo', 'DEF456'),
       (3, 'Chevrolet', 'Camaro', 'Negro', 'GHI789'),
       (4, 'Volkswagen', 'Golf', 'Blanco', 'JKL012'),
       (5, 'Honda', 'Civic', 'Gris', 'MNO345');

INSERT INTO WORKSHOP_RECEIPTS (car_registration, start_date, end_date, price_of_pieces, hourly_rate, curr, description)
VALUES ('ABC123', '2023-05-01', '2023-05-05', 250.00, 40.00, 'USD', 'Reparación de frenos'),
       ('ABC123', '2023-05-02', '2023-05-03', 120.00, 50.00, 'EUR', 'Cambio de aceite'),
       ('GHI789', '2023-05-05', '2023-05-07', 180.00, 55.00, 'USD', 'Reparación de motor'),
       ('JKL012', '2023-05-03', '2023-05-06', 320.00, 60.00, 'EUR', 'Reemplazo de neumáticos'),
       ('MNO345', '2023-05-04', '2023-05-05', 90.00, 45.00, 'USD', 'Alineación y balanceo');